"""
src/config — namespaced configuration package.

All constants are re-exported here so existing code using
    from src.config import X
continues to work without any changes.

New code should import directly from the sub-module:
    from src.config.nba import NBA_HOME_ADVANTAGE
"""

from src.config.base import (
    # API credentials
    ODDS_API_KEY,
    EMAIL_PASSWORD,
    EMAIL_FROM,
    EMAIL_TO,
    # Odds API
    ODDS_API_BASE,
    PREFERRED_BOOK,
    FALLBACK_BOOKS,
    # Sport keys + labels
    NBA_SPORT,
    MLB_SPORT,
    NFL_SPORT,
    NHL_SPORT,
    IPL_SPORT,
    WNBA_SPORT,
    MLS_SPORT,
    SPORT_LABELS,
    SPORT_ACTIVE_MONTHS,
    # Betting parameters
    DAILY_BUDGET,
    ROBINHOOD_COMMISSION,
    KELLY_FRACTION,
    MIN_EDGE,
    MAX_SINGLE_BETS,
    MAX_PARLAYS,
    MAX_PROPS_PER_SPORT,
    MIN_PARLAY_LEG_EDGE,
    # Cross-sport signals
    LINE_MOVE_THRESHOLD,
    SCHEDULE_LOAD_THRESHOLDS,
    # Output
    REPORT_DIR,
    REPORT_FILE,
    HISTORY_FILE,
)

from src.config.nba import (
    NBA_HOME_ADVANTAGE,
    NBA_BACK_TO_BACK_PENALTY,
    NBA_REST_BONUS_PER_DAY,
    NBA_RECENT_FORM_WEIGHT,
    NBA_PLAYOFF_SCORING_FACTOR,
    NBA_PLAYOFF_PACE_FACTOR,
    NBA_PLAYOFF_RECENT_WEIGHT,
    NBA_TOTAL_STD,
    NBA_PLAYOFF_TOTAL_STD,
)

from src.config.mlb import (
    MLB_HOME_ADVANTAGE,
    MLB_BACK_TO_BACK_PENALTY,
    MLB_REST_BONUS_PER_DAY,
    MLB_PLAYOFF_SCORING_FACTOR,
    MLB_PLAYOFF_STARTER_IP,
    MLB_PLAYOFF_RECENT_WEIGHT,
    MLB_RECENT_FORM_WEIGHT,
)

from src.config.nhl import (
    NHL_PLAYOFF_SCORING_FACTOR,
)

from src.config.ipl import (
    IPL_HOME_ADV,
    IPL_RECENT_WEIGHT,
)

from src.config.wnba import (
    WNBA_HOME_ADVANTAGE,
    WNBA_BACK_TO_BACK_PENALTY,
    WNBA_RECENT_WEIGHT,
    WNBA_SOS_WEIGHT,
    WNBA_SPREAD_STD,
    WNBA_REPLACEMENT_RATE,
    WNBA_MAX_LINEUP_PENALTY,
    WNBA_STATUS_WEIGHTS,
)

from src.config.mls import (
    MLS_LEAGUE_HOME_XG,
    MLS_LEAGUE_AWAY_XG,
    MLS_RECENT_WEIGHT,
    MLS_MIN_HOME_GAMES,
    MLS_HOME_ADV_DEFAULT,
    MLS_STRONG_VENUE_ADV,
    MLS_MAX_INJURY_PENALTY,
    MLS_DC_RHO,
    MLS_STRONG_VENUES,
)

__all__ = [
    # base
    "ODDS_API_KEY", "EMAIL_PASSWORD", "EMAIL_FROM", "EMAIL_TO",
    "ODDS_API_BASE", "PREFERRED_BOOK", "FALLBACK_BOOKS",
    "NBA_SPORT", "MLB_SPORT", "NFL_SPORT", "NHL_SPORT",
    "IPL_SPORT", "WNBA_SPORT", "MLS_SPORT",
    "SPORT_LABELS", "SPORT_ACTIVE_MONTHS",
    "DAILY_BUDGET", "ROBINHOOD_COMMISSION", "KELLY_FRACTION", "MIN_EDGE",
    "MAX_SINGLE_BETS", "MAX_PARLAYS", "MAX_PROPS_PER_SPORT", "MIN_PARLAY_LEG_EDGE",
    "LINE_MOVE_THRESHOLD", "SCHEDULE_LOAD_THRESHOLDS",
    "REPORT_DIR", "REPORT_FILE", "HISTORY_FILE",
    # nba
    "NBA_HOME_ADVANTAGE", "NBA_BACK_TO_BACK_PENALTY", "NBA_REST_BONUS_PER_DAY",
    "NBA_RECENT_FORM_WEIGHT", "NBA_PLAYOFF_SCORING_FACTOR", "NBA_PLAYOFF_PACE_FACTOR",
    "NBA_PLAYOFF_RECENT_WEIGHT", "NBA_TOTAL_STD", "NBA_PLAYOFF_TOTAL_STD",
    # mlb
    "MLB_HOME_ADVANTAGE", "MLB_BACK_TO_BACK_PENALTY", "MLB_REST_BONUS_PER_DAY",
    "MLB_PLAYOFF_SCORING_FACTOR", "MLB_PLAYOFF_STARTER_IP", "MLB_PLAYOFF_RECENT_WEIGHT",
    "MLB_RECENT_FORM_WEIGHT",
    # nhl
    "NHL_PLAYOFF_SCORING_FACTOR",
    # ipl
    "IPL_HOME_ADV", "IPL_RECENT_WEIGHT",
    # wnba
    "WNBA_HOME_ADVANTAGE", "WNBA_BACK_TO_BACK_PENALTY", "WNBA_RECENT_WEIGHT",
    "WNBA_SOS_WEIGHT",
    "WNBA_SPREAD_STD", "WNBA_REPLACEMENT_RATE", "WNBA_MAX_LINEUP_PENALTY",
    "WNBA_STATUS_WEIGHTS",
    # mls
    "MLS_LEAGUE_HOME_XG", "MLS_LEAGUE_AWAY_XG", "MLS_RECENT_WEIGHT",
    "MLS_MIN_HOME_GAMES", "MLS_HOME_ADV_DEFAULT", "MLS_STRONG_VENUE_ADV",
    "MLS_MAX_INJURY_PENALTY", "MLS_STRONG_VENUES", "MLS_DC_RHO",
]
